
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message
spec:
  selector:
    matchLabels:
      app: message
      tier: backend
      phase: test
  replicas: 1
  template:
    metadata:
      labels:
        app: message
        tier: backend
        phase: test
    spec:
      containers:
      - name: chat
        image: gambarini/grpc-demo
        imagePullPolicy: Always
        args:
        - messagesvc/main.go
        ports:
        - containerPort: 80