kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  client-body-timeout: "3600"
  client-header-timeout: "3600"
  error-log-level: info
  keep-alive: "3600"
  proxy-buffering: "off"
  proxy-request-buffering: "off"
  proxy-stream-timeout: "3600"
  ssl-session-timeout: "3600"
  upstream-keepalive-connections: "3600"
  proxy-connect-timeout: "3600"
  proxy-read-timeout: "3600"
  proxy-send-timeout: "3600"