apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq-autocluster
        image: gambarini/rabbitmq-autocluster:latest

        imagePullPolicy: Always
        env:

          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

          - name: ERLANG_COOKIE
            valueFrom:
              secretKeyRef:
                name: erlang.cookie
                key: erlang.cookie
        command:
          - "/start.sh"