apiVersion: v1
kind: Service
metadata:
  name: contactsvc-service
  labels:
    app: contactsvc
    tier: backend
    phase: test
spec:
  type: NodePort
  ports:
  - port: 30002
    nodePort: 30002
    targetPort: 30002
    name: http
  selector:
    app: contactsvc
    tier: backend
    phase: test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: contactsvc
spec:
  selector:
    matchLabels:
      app: contactsvc
      tier: backend
      phase: test
  replicas: 1
  template:
    metadata:
      labels:
        app: contactsvc
        tier: backend
        phase: test
    spec:
      containers:
      - name: chatsvc
        image: gambarini/grpc-demo
        imagePullPolicy: Never
        args:
        - servers/contactsvc/main.go
        ports:
        - containerPort: 30002